# The format of this config file is 'key = value'.
# The key has the format 'model.scenario.key'. Value is mostly int64_t.
# Model maybe '*' as wildcard. In that case the value applies to all models.
# All times are in milli seconds
#
# qwen3-vl-235b-a22b.*.min_query_count = 10
# qwen3-vl-235b-a22b.*.performance_sample_count_override = 10
qwen3-vl-235b-a22b.*.target_qps = 1.0
qwen3-vl-235b-a22b.*.min_duration = 0
